name: TPControl
version: ${project.version}
description: ${project.description}
website: ${project.url}
author: [Barney Gale, Deaygo, c45y, slide, Challenger2]
main: nu.nerd.tpcontrol.TPControl
softdepend: [Vault, WorldBorder, WorldGuard]
api-version: 1.13

permissions:
    tpcontrol.level.*:
        description: Teleport user class.
    tpcontrol.tppos:
        description: Allows a player to use tppos
    tpcontrol.back:
        descrption: Allows a player to teleport back to their previous location
    tpcontrol.warp.*:
        description: Allows a player to warp to any warp
    tpcontrol.setwarp:
        description: Allows a player to set a warp location
    tpcontrol.delwarp:
        description: Allows a player to delete a warp
    tpcontrol.admin:
        description: Allows use of /tpcontrol
    tpcontrol.randloc:
        description: Allows use of /randloc
    tpcontrol.home:
        description: Allows use of /home, /sethome, /delhome, and /listhomes.
        default: op
    tpcontrol.homeadmin:
        description: Allows admin functions to be used on the /home suite
        default: op
        children:
            tpcontrol.home: true

description: 
    Simple, configurable, tiered teleport plugin with allow/ask/deny modes.
commands:
    tpcontrol:
        description: TPControl admin functions
        permission: tpcontrol.admin
    tp:
        description: Teleport to another player
        usage: |
           /tp <player> - teleport to another player
    back:
        description: Teleport back to your previous location
        usage: |
           /back - teleport back to your previous location
    tppos:
        description: Teleport to a position
        usage: |
           /tppos [<world>] <x> <y> <z> - teleport to location
        permission: tpcontrol.tppos
    tphere:
        description: Teleport another player to you
        usage: |
           /tphere <player> - teleport another player to you
    tpmode:
        description: Restrict who can teleport to you
        usage: |
            /tpmode - show current mode
            /tpmode allow|ask|deny - change mode
    tpallow:
        description: Accept a teleport request
        usage: |
            /tpallow - accepts most recent teleport request
    tpdeny:
        description: Denies a teleport request
        usage: |
            /tpdeny - denies most recent teleport request
    tpfriend:
        description: Add a player to your teleport whitelist
        usage: |
            /tpfriend <player> - adds given player to whitelist
    tpunfriend:
        description: Removes a player from your teleport whitelist
        usage: |
            /tpunfriend <player> - removes given player from whitelist
    tpblock:
        description: Add a player to your teleport blacklist
        usage: |
            /tpblock <player> - adds given player to blacklist
    tpunblock:
        description: Removes a player from your teleport blocklist
        usage: |
            /tpunblock <player> - removes given player from blacklist
    warps:
        description: Lists the available warps
        usag: |
            /warps
    warp:
        description: Warp to a specific warp
        usage: |
            /warp <warp>
    setwarp:
        description: Set a warp location
        usage: |
            /setwarp <warp>
    delwarp:
        description: Remove a warp
        usage: |
            /delwarp <warp>
    cancelwarp:
        description: Cancel a warp warmup
        usage: |
            /cancelwarp
    randloc:
        description: Teleport to a random location
        permission: tpcontrol.randloc
        usage: |
            /randloc
    home:
        description: Teleport to a saved location
        permission: tpcontrol.home
        usage: |
            /<command> [[<player>] <name>]
    sethome:
        description: Save a named location
        permission: tpcontrol.home
        usage: |
             /<command> [<name>] [{public | unlisted | private}]
    listhomes:
        description: List saved locations
        aliases: [lshomes]
        permission: tpcontrol.home
        usage: |
            /<command> [<player>]
    delhome:
        description: Delete a saved location
        aliases: [rmhome]
        permission: tpcontrol.home
        usage: |
            /<command> [<player>] <home>
