name: TPControl
version: ${project.version}
description: ${project.description}
author: [Barney Gale, Deaygo, c45y, Nullsquare]
main: nu.nerd.tpcontrol.TPControl
permissions:
    tpcontrol.level.*:
        description: Teleport user class.
    tpcontrol.tppos:
        description: Allows a player to use tppos
description: 
    Simple, configurable, tiered teleport plugin with allow/ask/deny modes.
commands:
    tp:
        description: Teleport to another player
        usage: |
           /tp <player> - teleport to another player
    back:
        description: Teleport back to your previous location
        usage: |
           /back - teleport back to your previous location
        permission: tpcontrol.back
    tppos:
        description: Teleport to a position
        usage: |
           /tppos [<world>] <x> <y> <z> - teleport to location
        permission: tpcontrol.tppos
    tphere:
        description: Teleport another player to you
        usage: |
           /tphere <player> - teleport another player to you
    tpmode:
        description: Restrict who can teleport to you
        usage: |
            /tpmode - show current mode
            /tpmode allow|ask|deny - change mode
    tpallow:
        description: Accept a teleport request
        usage: |
            /tpallow - accepts most recent teleport request
    tpdeny:
        description: Denies a teleport request
        usage: |
            /tpdeny - denies most recent teleport request
    tpfriend:
        description: Add a player to your teleport whitelist
        usage: |
            /tpfriend <player> - adds given player to whitelist
    tpunfriend:
        description: Removes a player from your teleport whitelist
        usage: |
            /tpunfriend <player> - removes given player from whitelist
    tpblock:
        description: Add a player to your teleport blacklist
        usage: |
            /tpblock <player> - adds given player to blacklist
    tpunblock:
        description: Removes a player from your teleport blocklist
        usage: |
            /tpunblock <player> - removes given player from blacklist
    addwarp:
        description: Adds a warp to the list
        usage: |
            /addwarp <warpname>
    delwarp:
        description: Removes a warp from the list
        usage: |
            /delwarp <warpname>
    warp:
        description: Warp to a specified warp
        usage: |
            /warp <warpname>
    warps:
        description: List warps
        usage: |
            /listwarps
    addhome:
        description: Add a personal warp-style home
        usage: |
            /addhome <homename>
    delhome:
        description: Delete a personal home
        usage: |
            /delhome <homename>
    home:
        description: Teleport to your given home
        usage: |
            /home <homename>
    homes:
        description: Show your homes
        usage: |
            /homes
